/**
 * @license
 * Copyright 2026 Google LLC
 * SPDX-License-Identifier: Apache-2.0
 */

import {Client} from '@google-cloud/vertexai';
import {AgentEngineSandboxCodeExecutor, LlmAgent} from '@google/adk';
import {responseProcessor} from '@google/adk/agents/processors/code_execution_request_processor.js';
import {FinishReason} from '@google/genai';
import {describe, expect, it, vi} from 'vitest';
import {
  createRunner,
  GeminiWithMockResponses,
  RawGenerateContentResponse,
} from '../test_case_utils.js';

describe('Agent with AgentEngineSandboxCodeExecutor', () => {
  it('executes code generated by the agent', async () => {
    const mockResponses: RawGenerateContentResponse[] = [
      {
        candidates: [
          {
            content: {
              parts: [
                {
                  text: 'Here is the code to print hello:\n```python\nprint("hello")\n```',
                },
              ],
              role: 'model',
            },
            finishReason: FinishReason.STOP,
          },
        ],
      },
      {
        candidates: [
          {
            content: {
              parts: [{text: 'Execution was successful.'}],
              role: 'model',
            },
            finishReason: FinishReason.STOP,
          },
        ],
      },
    ];

    const mockClient = {
      agentEnginesInternal: {
        createInternal: vi.fn().mockResolvedValue({
          name: 'operations/create-engine-op',
          done: true,
          response: {
            name: 'projects/test-project/locations/us-central1/reasoningEngines/123',
          },
        }),
        sandboxes: {
          getInternal: vi.fn().mockResolvedValue({
            state: 'STATE_RUNNING',
          }),
          createInternal: vi.fn().mockResolvedValue({
            name: 'operations/create-sandbox-op',
            done: true,
            response: {
              name: 'projects/test-project/locations/us-central1/reasoningEngines/123/sandboxEnvironments/456',
            },
          }),
          executeCodeInternal: vi.fn().mockResolvedValue({
            outputs: [
              {
                mimeType: 'application/json',
                data: Buffer.from(
                  JSON.stringify({msg_out: 'hello', msg_err: ''}),
                ).toString('base64'),
              },
            ],
          }),
        },
      },
    };

    const executor = new AgentEngineSandboxCodeExecutor({
      projectId: 'test-project',
      client: mockClient as unknown as Client,
    });

    const model = new GeminiWithMockResponses(mockResponses);
    const agent = new LlmAgent({
      model,
      name: 'coderAgent',
      description: 'An agent that writes and runs code',
      instruction: 'Write code to solve the user request.',
      codeExecutor: executor,
      responseProcessors: [responseProcessor],
    });

    const {run} = await createRunner(agent);

    // eslint-disable-next-line @typescript-eslint/no-explicit-any
    const events: any[] = [];
    for await (const event of run('Print hello')) {
      events.push(event);
    }

    // We expect events for:
    // 1. User message (handled by runner)
    // 2. Model response with code
    // 3. Execution result
    // 4. Final model response

    expect(events.length).toBeGreaterThanOrEqual(3);

    // Check if we got a code execution result event
    const hasExecutionResult = events.some(
      (e) =>
        e.content?.parts?.some(
          (p: {text?: string}) => p.text && p.text.includes('hello'),
        ) ||
        (e.content?.parts?.[0]?.inlineData?.data &&
          Buffer.from(e.content.parts[0].inlineData.data, 'base64')
            .toString('utf-8')
            .includes('hello')),
    );

    expect(hasExecutionResult).toBe(true);
  });
});
