/**
 * @license
 * Copyright 2026 Google LLC
 * SPDX-License-Identifier: Apache-2.0
 */

import {
  Event,
  FunctionTool,
  InMemoryRunner,
  LlmAgent,
  StreamingMode,
} from '@google/adk';
import {createUserContent} from '@google/genai';
import * as dotenv from 'dotenv';
import * as fs from 'fs';
import * as path from 'path';
import {describe, expect, it} from 'vitest';
import {z} from 'zod';

const envPath = path.resolve(__dirname, '.env');
const envExists = fs.existsSync(envPath);

if (envExists) {
  dotenv.config({path: envPath});
}

const MODELS_TO_TEST = [
  'gemini-2.5-flash',
  'gemini-2.5-pro',
  'gemini-3-flash-preview',
  'gemini-3.1-flash-lite',
  'gemini-3.1-pro-preview',
  'gemini-pro-latest',
  'gemini-flash-lite-latest',
  'gemini-flash-latest',
];

const MOCK_FORECAST_TOOL = new FunctionTool({
  name: 'showForecastChart',
  description: 'Show the forecast chart for a location',
  parameters: z.object({location: z.string()}),
  execute: (args) => `Forecast chart for ${args.location} shown.`,
});

describe('E2E Live Model Streaming & Tool Call History', () => {
  const apiKey = process.env.GEMINI_API_KEY || process.env.GOOGLE_GENAI_API_KEY;
  const hasLiveCredentials = !!apiKey;

  // Run E2E tests for each model sequentially
  describe.skipIf(!hasLiveCredentials).each(MODELS_TO_TEST)(
    `Model: %s`,
    (modelName: string) => {
      it(`should successfully execute SSE streaming and preserve tool calls unmocked for ${modelName}`, async () => {
        const agent = new LlmAgent({
          name: 'e2e_streaming_agent',
          model: modelName,
          instruction: 'You must call showForecastChart for San Francisco.',
          tools: [MOCK_FORECAST_TOOL],
        });

        const runner = new InMemoryRunner({
          agent,
          appName: 'e2e_streaming_test',
        });

        const session = await runner.sessionService.createSession({
          appName: 'e2e_streaming_test',
          userId: 'e2e_user',
        });

        const results: Event[] = [];
        for await (const event of runner.runAsync({
          userId: 'e2e_user',
          sessionId: session.id,
          newMessage: createUserContent('Show me the forecast.'),
          runConfig: {streamingMode: StreamingMode.SSE},
        })) {
          results.push(event);
        }

        // Verify that the run completed successfully and yielded events
        expect(results.length).toBeGreaterThanOrEqual(1);

        // Find the tool call event in the results (if any was generated by the model)
        const toolCallEvents = results.filter(
          (event) =>
            event.author === 'e2e_streaming_agent' &&
            event.content?.parts?.some((part) => part.functionCall),
        );

        if (toolCallEvents.length > 0) {
          expect(
            toolCallEvents[0].content?.parts?.[0]?.functionCall?.name,
          ).toBe('showForecastChart');

          // Find the tool execution event in the results
          const toolResponseEvents = results.filter(
            (event) =>
              event.author === 'e2e_streaming_agent' &&
              event.content?.parts?.some((part) => part.functionResponse),
          );
          expect(toolResponseEvents.length).toBeGreaterThanOrEqual(1);

          // Verify that the DB session history contains the tool call properly saved
          const dbSession = await runner.sessionService.getSession({
            appName: 'e2e_streaming_test',
            userId: 'e2e_user',
            sessionId: session.id,
          });

          expect(dbSession).toBeDefined();
          expect(dbSession!.events.length).toBeGreaterThanOrEqual(3);

          // Verify tool call exists in session DB history
          const dbToolCall = dbSession!.events.find((e) =>
            e.content?.parts?.some((p) => p.functionCall),
          );
          expect(dbToolCall).toBeDefined();
          expect(dbToolCall!.content?.parts?.[0]?.functionCall?.name).toBe(
            'showForecastChart',
          );
        }
      });
    },
    90000,
  );
});
