/**
 * @license
 * Copyright 2026 Google LLC
 * SPDX-License-Identifier: Apache-2.0
 */

import {Event} from '@google/adk';
import {describe, it} from 'vitest';
import {
  RawGenerateContentResponse,
  runTestCase,
} from '../../test_case_utils.js';
import {rootAgent} from './agent.js';
import turn1ExpectedEvents from './events_turn_1.json' with {type: 'json'};
import turn2ExpectedEvents from './events_turn_2.json' with {type: 'json'};
import turn3ExpectedEvents from './events_turn_3.json' with {type: 'json'};
import modelResponses from './model_responses.json' with {type: 'json'};

const testCase = {
  agent: rootAgent,
  turns: [
    {
      userPrompt: 'Hello, what can you do?',
      expectedEvents: turn1ExpectedEvents as Event[],
    },
    {
      userPrompt:
        'I want to get description of this PR https://github.com/google/adk-js/pull/276',
      expectedEvents: turn2ExpectedEvents as Event[],
    },
    {
      userPrompt: 'And what is the status of that PR?',
      expectedEvents: turn3ExpectedEvents as Event[],
    },
  ],
  modelResponses: modelResponses as RawGenerateContentResponse[],
};

/**
 * This integration test verifies that an agent equipped with skills
 * can successfully process requests to interact with GitHub issues and pull requests.
 *
 * Specifically, it:
 * 1. Uses the `runTestCase` utility to execute a multi-turn test case defined by `modelResponses`.
 * 2. Simulates a conversation where the user asks about the agent's capabilities, requests a PR description, and asks for the PR status.
 * 3. Verifies that the sequence of events generated by the agent matches the expected events stored in `events_turn_1.json`, `events_turn_2.json`, and `events_turn_3.json`.
 *
 * This test ensures the agent correctly handles tool calls and state across multiple turns.
 */
describe('Agent with skills for GitHub interaction', () => {
  it('should process model response and produce events', async () => {
    await runTestCase(testCase);
  });
});
